### ISSUE TITLE
无法导出x9或x10文件

### ISSUE THREAD

**Issue by zhu1024** [crifan/cpu_emulator_unicorn#1]
按照您的教程，我成功搭建了环境和文件目录格式，但是我无法使用lldb工具导出x9和x10两个段的实际数据值到文件，请问可以分享这两个文件，或者介绍一下导出方法么

**Comment by crifan** [comment]
> 介绍一下导出方法

教程中，已有导出方法，详见：
[导出lldb调试时x9和x10两个段的实际数据值到文件](https://book.crifan.org/books/cpu_emulator_unicorn/website/summary_note/common_issue/uc_err_map/batch_fix_uc_err_map.html#%E5%AF%BC%E5%87%BAlldb%E8%B0%83%E8%AF%95%E6%97%B6x9%E5%92%8Cx10%E4%B8%A4%E4%B8%AA%E6%AE%B5%E7%9A%84%E5%AE%9E%E9%99%85%E6%95%B0%E6%8D%AE%E5%80%BC%E5%88%B0%E6%96%87%E4%BB%B6)

**Comment by crifan** [comment]
previous answered it
